In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import pickle
import utils


2022-12-25 17:05:29.466117: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-25 17:05:30.208193: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-12-25 17:05:30.208220: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-12-25 17:05:32.521385: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2022-

In [2]:
data = pd.read_csv("../cora/cora.content", sep="\t", header=None, index_col=0)

# Load preprocessed data
with open("../cora/papers.pkl", "rb") as f:
    papers = pickle.load(f)
with open("../cora/graph_info.pkl", "rb") as f:
    graph_info = pickle.load(f)

edges = graph_info[1]
x=np.array(edges).T
# Sort the edges for faster aggregation (by using segment_sum instead of unsorted_segment_sum)
# This is only used for the segment_sum-based model.
new_edges = x[x[:, 0].argsort()].T
graph_info = (graph_info[0], new_edges)

# Build an adjacency matrix encoding the input graph
A = utils.build_adj_matrix(x, graph_info[0].shape[0], symmetrize=True, normalize=True)

2022-12-25 17:10:33.763208: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-12-25 17:10:33.765223: W tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)
2022-12-25 17:10:33.767306: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (newhp): /proc/driver/nvidia/version does not exist
2022-12-25 17:10:33.797619: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-25 17:10:33.829593: W tensorflow/tsl/framework/cpu_allocator_impl.cc:8

(5429, 2) 2708


In [37]:
adj_df

0     1     2     3     4     5     6     7     8     9     ...  1423  \
0      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
1      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
2703   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2704   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2705   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2706   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2707   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0  ...   0.0   

      1424  1425  1426  1427  1428  1429  1430  1431  1432  
0      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3      0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0  
4      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
2703   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2704   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2705   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2706   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2707   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[2708 rows x 1433 columns]

In [42]:
papers

paper_id  term_0  term_1  term_2  term_3  term_4  term_5  term_6  \
0          462       0       0       0       0       0       0       0   
1         1911       0       0       0       0       0       0       0   
2         2002       0       0       0       0       0       0       0   
3          248       0       0       0       0       0       0       0   
4          519       0       0       0       0       0       0       0   
...        ...     ...     ...     ...     ...     ...     ...     ...   
2703      2370       0       0       0       0       0       0       0   
2704      2371       0       0       0       0       0       0       0   
2705      2372       0       0       0       0       0       0       0   
2706       955       0       0       0       0       1       0       0   
2707       376       0       0       0       0       0       0       0   

      term_7  term_8  ...  term_1424  term_1425  term_1426  term_1427  \
0          0       0  ...          0          0          1          0   
1          0       0  ...          0          1          0          0   
2          0       0  ...          0          0          0          0   
3          0       0  ...          0          0          0          0   
4          0       0  ...          0          0          0          0   
...      ...     ...  ...        ...        ...        ...        ...   
2703       0       0  ...          0          0          0          0   
2704       0       0  ...          0          0          0          0   
2705       0       0  ...          0          0          0          0   
2706       0       0  ...          0          0          0          0   
2707       0       0  ...          0          0          0          0   

      term_1428  term_1429  term_1430  term_1431  term_1432  subject  
0             0          0          0          0          0        2  
1             0          0          0          0          0        5  
2             0          0          0          0          0        4  
3             0          0          0          0          0        4  
4             0          0          0          0          0        3  
...         ...        ...        ...        ...        ...      ...  
2703          0          0          0          0          0        1  
2704          0          0          0          0          0        1  
2705          0          0          0          0          0        1  
2706          0          0          0          0          0        0  
2707          0          0          0          0          0        2  

[2708 rows x 1435 columns]

In [41]:
data

1  2  3  4  5  6  7  8  9  10  ...  1425  1426  1427  1428  1429  \
0                                       ...                                 
31336    0  0  0  0  0  0  0  0  0   0  ...     0     0     1     0     0   
1061127  0  0  0  0  0  0  0  0  0   0  ...     0     1     0     0     0   
1106406  0  0  0  0  0  0  0  0  0   0  ...     0     0     0     0     0   
13195    0  0  0  0  0  0  0  0  0   0  ...     0     0     0     0     0   
37879    0  0  0  0  0  0  0  0  0   0  ...     0     0     0     0     0   
...     .. .. .. .. .. .. .. .. ..  ..  ...   ...   ...   ...   ...   ...   
1128975  0  0  0  0  0  0  0  0  0   0  ...     0     0     0     0     0   
1128977  0  0  0  0  0  0  0  0  0   0  ...     0     0     0     0     0   
1128978  0  0  0  0  0  0  0  0  0   0  ...     0     0     0     0     0   
117328   0  0  0  0  1  0  0  0  0   0  ...     0     0     0     0     0   
24043    0  0  0  0  0  0  0  0  0   0  ...     0     0     0     0     0   

         1430  1431  1432  1433                   label  
0                                                        
31336       0     0     0     0         Neural_Networks  
1061127     0     0     0     0           Rule_Learning  
1106406     0     0     0     0  Reinforcement_Learning  
13195       0     0     0     0  Reinforcement_Learning  
37879       0     0     0     0   Probabilistic_Methods  
...       ...   ...   ...   ...                     ...  
1128975     0     0     0     0      Genetic_Algorithms  
1128977     0     0     0     0      Genetic_Algorithms  
1128978     0     0     0     0      Genetic_Algorithms  
117328      0     0     0     0              Case_Based  
24043       0     0     0     0         Neural_Networks  

[2708 rows x 1434 columns]

In [60]:
np.random.choice(range(12))

1

In [51]:
graph_info[1]

array([[   0,    0,    0, ..., 2707, 2707, 2707],
       [1218,  809, 1217, ...,  152,  345, 1897]])

In [49]:
graph_info

(<tf.Tensor: shape=(2708, 1433), dtype=float32, numpy=
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)>,
 array([[   0,    0,    0, ..., 2707, 2707, 2707],
        [1218,  809, 1217, ...,  152,  345, 1897]]))

In [47]:
from numpy.linalg import svd
A = graph_info[0].numpy()
U,d,Vt = svd(A)
Uk = U[:,:50]
adj_df = pd.DataFrame(data=Uk)
full_df = pd.concat([papers, adj_df], axis=1)

In [16]:
data.rename(columns={1434: 'label'}, inplace=True)

In [40]:
full_df

paper_id  term_0  term_1  term_2  term_3  term_4  term_5  term_6  \
0          462       0       0       0       0       0       0       0   
1         1911       0       0       0       0       0       0       0   
2         2002       0       0       0       0       0       0       0   
3          248       0       0       0       0       0       0       0   
4          519       0       0       0       0       0       0       0   
...        ...     ...     ...     ...     ...     ...     ...     ...   
2703      2370       0       0       0       0       0       0       0   
2704      2371       0       0       0       0       0       0       0   
2705      2372       0       0       0       0       0       0       0   
2706       955       0       0       0       0       1       0       0   
2707       376       0       0       0       0       0       0       0   

      term_7  term_8  ...  1423  1424  1425  1426  1427  1428  1429  1430  \
0          0       0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
1          0       0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
2          0       0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
3          0       0  ...   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   
4          0       0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
...      ...     ...  ...   ...   ...   ...   ...   ...   ...   ...   ...   
2703       0       0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
2704       0       0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
2705       0       0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
2706       0       0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
2707       0       0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   

      1431  1432  
0      0.0   0.0  
1      0.0   0.0  
2      0.0   0.0  
3      0.0   0.0  
4      0.0   0.0  
...    ...   ...  
2703   0.0   0.0  
2704   0.0   0.0  
2705   0.0   0.0  
2706   0.0   0.0  
2707   0.0   0.0  

[2708 rows x 2868 columns]

In [ ]:




# Shuffle the dataset. Since it is small, we can afford to make a copy
shuffled_data = data.sample(frac=1)
TRAINING_SIZE = 0.5
split_point = int(TRAINING_SIZE*data.shape[0])
train_data, test_data = np.array_split(shuffled_data, [split_point])

# Separate features and labels into numpy arrays
# We use the following brief helper function to avoid code repetition
def pop_label(data):
    # Separate features and label on the CORA dataset
    return data.drop(axis="columns", labels=1434).values, pd.get_dummies(data[1434]).values
train_vectors, train_labels = pop_label(train_data)
test_vectors, test_labels = pop_label(test_data)
